### ISSUE TITLE
高分屏适配后出现ui问题

### ISSUE THREAD

**Issue by bokutaki** [dream7180/foobox-cn#102]
标题下面有一行文本被歌词面板遮盖了，怎么调整标题那一块的行距和字体大小，或者该怎么调整歌词面板的高度？
![K IDWN_1FLS{4CQXN~X10%B](https://user-images.githubusercontent.com/44322263/165887059-b8821859-9bf0-4df0-a0f3-00ad0317c70d.png)

**Comment by bokutaki** [comment]
ESlyric原来就是自带的歌词面板，稍微调整了一下布局，ok了

**Comment by dream7180** [comment]
有遮盖吗？那是渐变效果啊

**Comment by bokutaki** [comment]
@dream7180 不是指歌词被遮盖，是有一行属性值
![E}LNK2V9A2K%{ULR)VIC 5](https://user-images.githubusercontent.com/44322263/170505245-4347acdd-6e1d-480c-ae5d-40a6748c7ceb.png)

**Comment by dB73LbeigXc** [comment]
<img width="524" alt="image" src="https://user-images.githubusercontent.com/11750269/170871257-4457f23f-6811-4a9a-83a3-9ff337547a5d.png">

任务栏这个图标不对劲哦，是我哪里没设置好吗？

**Comment by a1waysbeta** [comment]
> 是
这个应该是系统问题，win11 有一版有这个问题

**Comment by dB73LbeigXc** [comment]
> 

退回旧版本了
