### ISSUE TITLE
V6.1.6.10 版设置关闭为后台播放无效

### ISSUE THREAD

**Issue by antnesswcm** [dream7180/foobox-cn#103]
[V6.1.6.10](https://github.com/dream7180/foobox-cn/releases/tag/6.1.6.10)版本
![image](https://user-images.githubusercontent.com/58334061/168533350-f3484870-f3b0-409a-b39e-2168d2e29917.png)

**Comment by xjtu-blacksmith** [comment]
转载自 Gitee 仓库下方评论：

![图片](https://user-images.githubusercontent.com/42454373/170910830-8f1a2572-eb47-4b1d-bd0e-c4e7db384615.png)

不过对分栏界面应该设置不了“关闭:隐藏至托盘”这种功能了？

**Comment by github-24** [comment]
我也是这样，设置不了
