### ISSUE TITLE
如何给特定分组规则指定特定分组依据

### ISSUE THREAD

**Issue by shardine** [dream7180/foobox-cn#123]
![image](https://user-images.githubusercontent.com/75930744/185747547-e9302909-aa89-411b-9bd9-a79a71a971a0.png)

可不可以给某个播放列表设定一个分组依据，目前好像修改分组依据所有播放列表都变了。

**Comment by a1waysbeta** [comment]
1 分组模板里 选择对应的分组模板
2 底下 播放列表过滤 里面填入 对应播放列表名称，多个列表用 ; 隔开
或者 右键菜单播放列表过滤也可以，琢磨尝试一下

**Comment by shardine** [comment]
> 1 分组模板里 选择对应的分组模板 2 底下 播放列表过滤 里面填入 对应播放列表名称，多个列表用 ; 隔开 或者 右键菜单播放列表过滤也可以，琢磨尝试一下

感谢答复，这样可以了。还有点问题：播放列表过滤里怎么表达除了某个播放列表的含义
![image](https://user-images.githubusercontent.com/75930744/185781103-7ffd2b76-c68a-46a9-ab33-2e2934052ba8.png)
尝试了几个关键字都不行

**Comment by dream7180** [comment]
现在支持为播放列表创建独立的分组设定了
