### ISSUE TITLE
wsh面板有时候会莫名其妙崩溃

### ISSUE THREAD

**Issue by shardine** [dream7180/foobox-cn#124]

**Comment by a1waysbeta** [comment]
什么信息都没提供，无法诊断。崩溃之后控制台信息是什么？弹出的错误面板是什么？

**Comment by shardine** [comment]
> 什么信息都没提供，无法诊断。崩溃之后控制台信息是什么？弹出的错误面板是什么？

![image](https://user-images.githubusercontent.com/75930744/186166658-ad348efc-992e-41f1-9053-30c50831b0b7.png)
![image](https://user-images.githubusercontent.com/75930744/186166670-5e19c076-3520-40fd-94fb-6c4184678ae2.png)
![image](https://user-images.githubusercontent.com/75930744/186166677-7019c5d0-2e8f-412a-9e05-4b0e5b2c86dc.png)

之前忘记记录了，现在又一次出现
