### ISSUE TITLE
由歌词插件ESLyric导致的foobox崩溃

### ISSUE THREAD

**Issue by IntMainError** [dream7180/foobox-cn#136]
从6.6.11就有了，现在6.6.12还是没有修复，看不到崩溃原因

**Comment by IntMainError** [comment]
一般是在用ESLyric搜索歌词的时候崩溃，当然也有可能是其他原因

**Comment by dream7180** [comment]
用新版本试试

**Comment by IntMainError** [comment]
又崩溃了，而且崩溃前的操作没有保存，是在ESLyric检索其他网站时，我双击加载一个lrc，然后检索完毕后刷新列表时崩溃的，我没找到log
