### ISSUE TITLE
请教一个关于MPV插件的问题

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#137]
把视频播放面板放到可视化里后
有没有方法可以使foobar在音乐和视频间自动跳转可视化插件和MPV插件
就是播放音乐时面板显示winamp插件，播放视频时则自动显示视频。

**Comment by dream7180** [comment]
可以是可以但是这样影响太大了，没什么好处

**Comment by yiiyahui** [comment]
原来还想试下能不能整合成视频播放器
试了下插件，发现不达标，只能播下MV或音乐视频。
不过还是觉得可以整合在可视化里。只是不知道会有什么影响

**Comment by dream7180** [comment]
我也当作mpv的UI来用，能选音轨，能字幕，能硬解码，简单的电影能解决。
