### ISSUE TITLE
绿化版要怎么完整的覆盖安装？

### ISSUE THREAD

**Issue by github-24** [dream7180/foobox-cn#141]
压缩包导入新版后旧数据被覆盖了

**Comment by klxq520** [comment]
我是解压后覆盖的，感觉没什么问题

**Comment by github-24** [comment]
> 我是解压后覆盖的，感觉没什么问题

我是全部解压进去的，全部覆盖了

**Comment by shardine** [comment]
直接覆盖安装的话，原本的界面设置就被覆盖了。除了手动覆盖配置文件好像没什么别的办法，不过我上次从6.6.12更新到6.6.13覆盖了整个profile/configuration里面的数据，结果13的顶部栏变回了12。感觉现在的安装方式好复杂（
