### ISSUE TITLE
请问如何关闭曲目右键菜单“选择 → 发送到”

### ISSUE THREAD

**Issue by 7peanuts** [dream7180/foobox-cn#144]
好多次不小心点到了发送到，导致原播放列表被重置。
再问一下，如果被重置了，还能找回原先的播放列表吗？
![20221113111544](https://user-images.githubusercontent.com/82173614/201504064-1206b98e-25c6-4e4c-840b-847d8069d144.jpg)

**Comment by 7peanuts** [comment]
> 如果被重置了，还能找回原先的播放列表吗？

自己摸索出一个找回方法来，播放列表是在关闭播放器后才写入硬盘的。
所以发现误操作列表后，不要关闭播放器，找到 foobar2000 安装目录内的 `playlists-v1.4` 播放列表文件夹并备份，然后再关闭播放器，此时关闭之前更改过的播放列表会写入该目录，按文件修改日期排序，将刚刚更新的文件备份一下。
最后根据需要，选择要还原的播放列表就行了。

**Comment by shardine** [comment]
右键播放列表有个列表记录可以恢复。这个发送到着实误导人，我是用智能播放列表避免使用添加到发送到这些功能

**Comment by dream7180** [comment]
下个版本会在播放列表视图选项里添加一个是否开启的选项

**Comment by 7peanuts** [comment]
> 右键播放列表有个列表记录可以恢复。这个发送到着实误导人，我是用智能播放列表避免使用添加到发送到这些功能

这个智能列表厉害了，不过得需要歌曲文件元数据齐全，这就不太好办了。

**Comment by 7peanuts** [comment]
> 下个版本会在播放列表视图选项里添加一个是否开启的选项

抱歉，我没找到新版本 7.6 这个选项在哪
![20230222121202](https://user-images.githubusercontent.com/82173614/220520037-b167568a-8e3c-4cd0-b8b9-183385941e0c.jpg)
