### ISSUE TITLE
4k屏幕下界面太小了，可以设置么，求教求教

### ISSUE THREAD

**Issue by hdyard2017** [dream7180/foobox-cn#149]
求教各位大佬，在4k屏幕下界面太小，没办法正常使用，可以做界面设置么，没有找到相关设置来着

**Comment by flinhong** [comment]
菜单 > 帮助，有详细的分辨率适配说明吧

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: hdyard ***@***.***>
Sent: Monday, November 28, 2022 9:36:17 AM
To: dream7180/foobox-cn ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dream7180/foobox-cn] 4k屏幕下界面太小了，可以设置么，求教求教 (Issue #149)


求教各位大佬，在4k屏幕下界面太小，没办法正常使用，可以做界面设置么，没有找到相关设置来着

―
