### ISSUE TITLE
wasapi可以删除

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#150]
包内的wasapi插件可以去掉，1.6版本后默认输出是wasapi share和excusive，只是他名称没这么写。

**Comment by yiiyahui** [comment]
https://www.foobar2000.org/changelog

1.6

Default output mode is now WASAPI shared.

**Comment by hooke007** [comment]
插件是asion加的，foobar汉化的问题你可以直接向他本人反馈。这是他对你这个问题的解释。

https://www.cnblogs.com/asionwu/p/16967743.html#5141142
