### ISSUE TITLE
7.0的压缩包解压后怎么打开软件呢？体积只有10MB，是有问题吗？

### ISSUE THREAD

**Issue by xiwenchao** [dream7180/foobox-cn#153]
最新版本的压缩包解压后没看到有可执行文件

**Comment by yiiyahui** [comment]
> 最新版本的压缩包解压后没看到有可执行文件

此版非整合版，自行下载软件安装，把zip包里的文件解压到主目录运行即可

**Comment by xiwenchao** [comment]
> 

您好，我解压了以后再打开foobox，报错：

脚本引擎初始化失败 (Foobox playback & seekbar by dreamawake, CODE: 0x80020101)
控制台可查看更多信息(脚本错误的原因).


WSH 面板加强版 (Foobox playback & seekbar by dreamawake): Microsoft JScript 编译错误:
缺少 ';'
文件: C:\Software\foobar2000\themes\foobox\js_panels\bottombar.js
行: 203, 列: 6
	let _x2 = 2*zdpi, _x4=4*zdpi, _x5 = 5*zdpi, _x6 = 6*zdpi,  _x7 = 7*zdpi, _x13 = 13*zdpi, _x8 = 8*zdpi, _x9 = 9*zdpi, _x10 = 10*zdpi, _x12 = 12*zdpi, _x16 = 16*zdpi,

WSH 面板加强版 (Foobox Top Bar by dreamawake, Searchbox by Asion): Microsoft JScript 运行时错误:
'ButtonUI' 未定义
文件: C:\Software\foobar2000\themes\foobox\js_panels\topbar.js
行: 581, 列: 2
<源文本仅在编译时可用>


WSH 面板加强版 (Foobox simple playlist viewer for JSSB by dreamawake, Elia): Microsoft JScript 运行时错误:
对象不支持此属性或方法
文件: C:\Software\foobar2000\themes\foobox\js_panels\jsview_playlist.js
行: 315, 列: 2
<源文本仅在编译时可用>

WSH 面板加强版 (Library Tree by Wilb, Mod by dreamawake): Microsoft JScript 运行时错误:
溢出
文件: C:\Software\foobar2000\themes\foobox\js_common\GdiFont.js
行: 15, 列: 2
<源文本仅在编译时可用>

WSH 面板加强版 (Foobox WSH Rating & Track Info by dreamawake): Microsoft JScript 运行时错误:
'DT_LEFT' 未定义
文件: C:\Software\foobar2000\themes\foobox\js_common\JScommon.js
行: 116, 列: 1
<源文本仅在编译时可用>

等等信息

**Comment by UmbraNix** [comment]
这是一次改变比较大的更新，UI从CUI转为DUI，因此不可以直接覆盖
如同ReadMe所说，你可以直接在https://www.cnblogs.com/asionwu/p/16967743.html这里下载整合好的foobar。
我比较推荐删除原来的所有文件并重新安装。
我个人觉得比较重要的备份有%foobarpath%/profile下的configuration, index-data, library, playlist-v1.4，实在不行，可以备份整个profile文件夹
顺带一提，我个人觉得新的UI颜值没有原来的高……期待之后的更新

**Comment by xiwenchao** [comment]
> 

好的，感谢回复！

**Comment by yiiyahui** [comment]
> > 
> 
> 好的，感谢回复！

你的问题应该是之前的插件（如cui）所致。此版为原生DUI界面。要更换此版，删除原有user-components目录的第三方插件（仅保留与zip包里的三个同名插件）及"configuration"目录。忘记还有什么目录了。建议直接备份播放列表后重新安装。

**Comment by starlifezzz** [comment]
为啥不看readme呢。。。。。。
