### ISSUE TITLE
请求发布完整版本

### ISSUE THREAD

**Issue by Masir01** [dream7180/foobox-cn#160]
因为平时自己也有更新或者添加一些组件,  7.1的更新覆盖进去整个界面只能显示白框无法显示内容, 显示了一些冲突以及解析的错误,  里面还涉及到一些配置. 目前无法使用更新包. 希望能发布完整版本.

**Comment by cmhdream** [comment]
切換成 7.2 雖然成功 但是喜歡暗黑模式，但是有些區域還是白色 很傷眼睛

**Comment by Masir01** [comment]
好的  谢谢    .     现在好了.

**Comment by Masir01** [comment]
> 切換成 7.2 雖然成功 但是喜歡暗黑模式，但是有些區域還是白色 很傷眼睛
确实   能搞个纯黑的就好了 .  并且说实话 我还蛮喜欢以前那种专辑图片变色的

**Comment by dream7180** [comment]
暗黑模式是支持的，要foobar2000 2.0了

**Comment by rianjskis** [comment]
> 你装asion的汉化版，然后把foobox7.x的包拷进去就行了，不要用CUI，用DUI（默认用户界面）

你好作者，我安装得asion的最新汉化版，再把https://github.com/dream7180/foobox-cn/releases/download/7.2/foobox_7.2.7z 解压拷贝进去，还是不能像v6.6.13版本那样显示而是全白的这种
![1](https://user-images.githubusercontent.com/86937445/210746998-fe58741c-d77a-44de-8504-888bac8d8053.png)

**Comment by Masir01** [comment]
> > 你装asion的汉化版，然后把foobox7.x的包拷进去就行了，不要用CUI，用DUI（默认用户界面）
> 
> 你好作者，我安装得asion的最新汉化版，再把 https://github.com/dream7180/foobox-cn/releases/download/7.2/foobox_7.2.7z 解压拷贝进去，还是不能像v6.6.13版本那样显示而是全白的这种 ![1](https://user-images.githubusercontent.com/86937445/210746998-fe58741c-d77a-44de-8504-888bac8d8053.png)

新版是这样的, 都一样
