### ISSUE TITLE
增加对x64版本的支持

### ISSUE THREAD

**Issue by I-love-study** [dream7180/foobox-cn#161]
现在 release 中的压缩包只支持 32位 的 foobar2000
希望能够增加对 64位 版本的打包

**Comment by dream7180** [comment]
嗯，我也是这样想的，得等jsplitter这个组件发64位版，应该会有的，项目还活着

**Comment by cmhdream** [comment]
目前 x32 的全黑模式 比 1.6 好很多
![About foobar200001-20_103051](https://user-images.githubusercontent.com/24859526/213605550-2a2e098a-e89f-4b9a-86be-b68f4c956e0e.jpg)

**Comment by I-love-study** [comment]
已于 [v7.26](https://github.com/dream7180/foobox-cn/releases/tag/7.26) 及之后版本支持
