### ISSUE TITLE
又来提交问题了

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#164]
1：播放状态的图标丢失了，不知是不是有意更改的。
2：新建/已有播放列表都无法重命名，只能通过修改index文件。
![螢幕擷取畫面_20230113_033931](https://user-images.githubusercontent.com/30188835/212271314-9df23974-cb2d-4462-a5f8-896e1416ddf2.png)

**Comment by dream7180** [comment]
1. 播放图标没改，一直都有
2. 重命名输入后回车生效

**Comment by yiiyahui** [comment]
> 1. 播放图标没改，一直都有，英文版的我看看是不是有问题，谢谢反馈
> 2. 重命名输入后回车生效

感谢！

另外有个建议，目前三个面板只有第二个浏览面板的功能菜单提供“发送到...----XXX列表”（已建立的播放列表），但是只能整张专辑（艺术家）发送。 想要发送单曲到某个播放列表只能通过媒体库面板的菜单“添加到当前列表”，这样就建立自定义列表略为不方便。

所以能不能考虑在浏览面板的右侧的列表，或者媒体库面板的树状列表的功能菜单添加“发送到....”

![螢幕擷取畫面_20230113_065947](https://user-images.githubusercontent.com/30188835/212305901-7051de73-5776-4e10-944a-0a1a1736a406.png)

**Comment by dream7180** [comment]
英文版的修复好了。第一个面板有这个子菜单的，但默认没有开启，可以进入foobox设置->播放列表视图里勾选一下就行了。

**Comment by yiiyahui** [comment]
> 英文版的修复好了。第一个面板有这个子菜单的，但默认没有开启，可以进入foobox设置->播放列表视图里勾选一下就行了。

大意了，没有发现 😂
再次感谢！
