### ISSUE TITLE
Milkdrop Cannot Use

### ISSUE THREAD

**Issue by NPU-Franklin** [dream7180/foobox-cn#17]
Sorry to bother you, but milkdrop seems cannot work properly on my computer, the OS of which is Windows10. Thanks a lot!

**Comment by Nanlon** [comment]
> Sorry to bother you, but milkdrop seems cannot work properly on my computer, the OS of which is Windows10. Thanks a lot!

You need to install [DirectX 9.0c](https://www.microsoft.com/en-us/download/details.aspx?id=8109) on your computer

**Comment by NPU-Franklin** [comment]
Thanks, I'll try it.:smile:
