### ISSUE TITLE
歌词高亮颜色经常关了，然后下首歌又自动打开

### ISSUE THREAD

**Issue by qxsny** [dream7180/foobox-cn#179]
求解决。然后我觉得这个高亮颜色可以自动从封面取色

**Comment by dream7180** [comment]
默认就是跟随主题，主题默认也是从封面取色的，不想跟随，可以在 foobox 设置里关闭跟随封面颜色

**Comment by RXrelax** [comment]
> 默认就是跟随主题，主题默认也是从封面取色的，不想跟随，可以在 foobox 设置里关闭跟随封面颜色

请问下这个foobox的专门的设置是在哪没有找到
