### ISSUE TITLE
建议以文件夹分组读取封面文件图片时，支持多个名字格式

### ISSUE THREAD

**Issue by life4rent119** [dream7180/foobox-cn#180]
现在好像只支持读取cover.jpg，建议增加 front.jpg 、folder.jpg，亦或是本身支持，只是我没有设置对？

![屏幕截图 2023-03-12 030426](https://user-images.githubusercontent.com/46873409/224507048-51657778-b84e-4bf8-b26e-d5ced0beaf5d.png)

**Comment by dream7180** [comment]
好的，下次更新加入，好像大家对这个不看重，所有一直单名称。
