### ISSUE TITLE
无法更改高亮颜色

### ISSUE THREAD

**Issue by cocochinoa** [dream7180/foobox-cn#184]
在使用布局改变颜色后，点击播放高亮颜色会变成黑色。

**Comment by cocochinoa** [comment]
![Uploading Snipaste_2023-03-21_08-46-02.png…]()

**Comment by cocochinoa** [comment]
![Snipaste_2023-03-21_08-46-02](https://user-images.githubusercontent.com/81227507/226495236-1fb97a34-49e7-45ce-8b82-5ad3b6abef5a.png)
![Snipaste_2023-03-21_08-46-10](https://user-images.githubusercontent.com/81227507/226495246-24182074-ae2c-4cec-9497-6dac3fb8415b.png)

**Comment by dream7180** [comment]
默认跟随封面颜色，设置为不跟随旧可以自定义了
