### ISSUE TITLE
按目录结构分组时封面显示错误

### ISSUE THREAD

**Issue by life4rent119** [dream7180/foobox-cn#186]
文件目录结构为：
-方季惟.-.[典藏岁月].专辑.(ape)
--cd1
--cd2

封面文件以”cover.jpg“分别存放于音轨所在目录

按”专辑（简单）“分组时显示正常如下图
![屏幕截图 2023-03-23 113344](https://user-images.githubusercontent.com/46873409/227095497-ad923095-6134-44f9-9451-a0067fdb0637.png)

按”目录结构“排序时显示如下，乱了，显示错的图片存放于其他同名CD1、CD2文件夹
![屏幕截图 2023-03-23 113409](https://user-images.githubusercontent.com/46873409/227095742-dd7eb420-1856-45f0-8fb0-4839dc9b2649.png)

**Comment by dream7180** [comment]
嗯，现在的目录分组逻辑有点过于简单，下个版本修正，谢谢反馈。
