### ISSUE TITLE
可否在“列”中加入“播放列表过滤"

### ISSUE THREAD

**Issue by hejiameiwoaini** [dream7180/foobox-cn#187]
您好，一直用您的作品，感佩您的坚持。有一个小建议：
可否在“列”中加入“播放列表过滤"
比如“等级”列只想让它在含有“等级”字样的播放列表中显示
随着列越来越多，我加入很多诸如ReplayGain、SKIP、Queue等自定义列
这些自定义列显然不希望在所有播放列表中都显示出来，都显示出来既显得臃肿，地方也不够
只希望他们在特定的播放列表中显示，所以
这个功能还是非常有用的
所以，希望加入下面两个功能：
1.设置自定义列在某些播放列表中显示
2.设置自定义列在某些播放列表中不显示

最后再次感谢您的作品，祝您发大财

**Comment by dream7180** [comment]
谢谢反馈，我的方向是淘汰播放列表过滤，改为保存单个列表的布局。目前在构思方案，看看能不能实现。

**Comment by dream7180** [comment]
7.11新版已经解决了这个问题
