### ISSUE TITLE
如何避免自动生成媒体库视图播放列表

### ISSUE THREAD

**Issue by shardine** [dream7180/foobox-cn#189]
每次点击封面浏览器都会自动生成媒体库试图播放列表，怎么不让它自动生成？

**Comment by dream7180** [comment]
这是右栏列表需要用的，总有个列表给它才行，如果不想看到这个列表，方法是切换到别的界面就删除这个列表，到回来又重新创建，这做法掩耳盗铃而且降低效率，还不如容下它。
