### ISSUE TITLE
面板排列保存问题！

### ISSUE THREAD

**Issue by 762033837** [dream7180/foobox-cn#193]
您好，版本更新的时候复制进去后原先的自定义排列喝设置都会还原到默认状态，可以否有个可以保存自己界面的功能？

**Comment by github-24** [comment]
> 您好，版本更新的时候复制进去后原先的自定义排列喝设置都会还原到默认状态，可以否有个可以保存自己界面的功能？

只解压themes文件夹就行了，profile文件夹不用
