### ISSUE TITLE
汉化 plus 版安装以后没有MusicTag，覆盖7.8版后还是没有

### ISSUE THREAD

**Issue by qsyyy** [dream7180/foobox-cn#195]
plus版没有，下载release覆盖安装以后还是没有MusicTag，我记得以前foobox有内置这个插件的吧？是我哪里没装对吗？

**Comment by dream7180** [comment]
自己下载musictag放在任意你想放的地方，然后再foobox设置--播放列表视图里设置好路径就可以了

**Comment by qsyyy** [comment]
>

抱歉，我没找到foobox设置界面在哪，我的界面跟你预览的图一样。
这是我的界面截图，请看一下
https://files.catbox.moe/73aweu.png

**Comment by qsyyy** [comment]
> 

我找foobox设置在哪了，原来在上方的属性栏右键菜单里
