### ISSUE TITLE
小小打击作者一下

### ISSUE THREAD

**Issue by ssxfssxf2000** [dream7180/foobox-cn#197]
工具里面的设置全都没了SACD什么的选项全没，难道都拿这软件听mp3?
不是应该拿来听SACD的么？这个软件应该是用来听无损音乐的（当然还有更好的软件），几百M一首那种DSF,DFF这类格式的，都搞错方向了吧，听mp3浪费了。
![无标题](https://user-images.githubusercontent.com/52859841/235133030-79f003e0-9878-4b22-946c-d5d4296036fe.jpg)

现在就是SACD根本没法听了，全是沙沙声，没法设置。
![无标题2](https://user-images.githubusercontent.com/52859841/235134180-7271fa7b-6764-4b6a-a249-eb739f7c8151.jpg)
![无标题3](https://user-images.githubusercontent.com/52859841/235134191-6a888bb7-4a6f-41ea-85e3-03795be1ce9b.jpg)

**Comment by ssxfssxf2000** [comment]
![无标题](https://user-images.githubusercontent.com/52859841/235139340-a8b3e243-6be3-4bc7-8c3c-707a2e866067.jpg)
这张专辑是越听越舒服哇，左下角的数字。

**Comment by dream7180** [comment]
我这只做界面，发布的包也只有和界面有关的组件，程序和其他组件一概不会添加，望知悉。我也不听mp3，无损起步。集成和扩展请下载asion的plus版或自行添加sacd组件。

**Comment by ssxfssxf2000** [comment]
OK，忘记这只是界面了，我自己去添加了插件用起来很棒，继续加油哦。
