### ISSUE TITLE
[BUG] 长距离拖动播放列表时组件崩溃

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#198]
![屏幕截图 2023-04-30 213737](https://user-images.githubusercontent.com/93318731/235355973-8f862afa-90cd-4409-84d0-0d310184133e.png)
如图所示，当左侧播放列表中的一个列表在目录中拖动较长距离时，有时会导致崩溃

**Comment by dream7180** [comment]
请描述清楚一点，不理解列表在目录中拖动较长距离是指什么情况，没能把崩溃还原出来，谢谢~

**Comment by Ptilopsis01** [comment]
> 请描述清楚一点，不理解列表在目录中拖动较长距离是指什么情况，没能把崩溃还原出来，谢谢~

因为我播放列表比较多，比如说我把最下面的一个播放列表拖到上面就需要一边按住向上拖动一边滚动滚轮，有时候就会出现这种崩溃

**Comment by dream7180** [comment]
我特意建了170多个列表还是没能试出崩溃的情况，麻烦你能录屏一小段看看是怎么产生的么？

**Comment by Ptilopsis01** [comment]
> 我特意建了170多个列表还是没能试出崩溃的情况，麻烦你能录屏一小段看看是怎么产生的么？


https://user-images.githubusercontent.com/93318731/235939160-eb95c708-abea-4f0d-9953-04394710f56d.mp4
大概就这样拖一拖就会崩，报错和之前一样（打码算是保护一下自己的xp）

**Comment by dream7180** [comment]
谢谢反馈，下次更新这个问题应该就解决了
