### ISSUE TITLE
希望可以支持文件夹/文件拖放

### ISSUE THREAD

**Issue by LeslieSong** [dream7180/foobox-cn#20]
文件夹/文件往播放列表里面拖动不支持，每次还需要覆盖安装一下asion汉化版本，但是部分配置文件又丢了……
希望支持一下文件拖放功能

**Comment by klxq520** [comment]
一直都能拖动添加啊

**Comment by LeslieSong** [comment]
> 一直都能拖动添加啊

这次更新后可以了
