### ISSUE TITLE
再来提个建议参考。

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#202]
不好意思，再来提下建议，供参考一下，下面粗略改了个效果图。
1：反正没有使用uihacks菜单肯定是存在的，那打开按纽似乎没有存在的必要（win下似乎crtl+o也是祖传快捷键）。另外，停止和暂停在使用上没有本质上的区别，这两个按纽我个人认为可以去掉。
2：始终觉得音量左侧的控制按纽比例有点偏大，视觉上显得有点不协调，如果缩小10%应该会好很多，不知道工作量大不大，或者在高DPI下有没有影响。（下图中shuffle按纽做了缩小）
![螢幕擷取畫面 2023-05-20 234634](https://github.com/dream7180/foobox-cn/assets/30188835/2df07f70-d812-43ca-9cb1-c477008ec0bc)

**Comment by yiiyahui** [comment]
忘了写了，图中上下曲目的两个按纽配合上次版本更新的实心播放按纽做了下修改效果，参考一下😊😊😊

**Comment by dream7180** [comment]
感谢建议，新版本将添加打开和停止按钮的显示选项，音量条缩小10%，至于左右的实心按钮没打算采纳，除非全局统一实心。

**Comment by dream7180** [comment]
和音量图标一样大的，不需要改动

**Comment by yiiyahui** [comment]
不一样大啊，肉眼可见的音量图标较小。因为他们离得很近。
![095437](https://github.com/dream7180/foobox-cn/assets/30188835/a762a743-3c91-458b-b69e-570573d27348)

**Comment by dream7180** [comment]
![图片](https://github.com/dream7180/foobox-cn/assets/18242221/e515d432-8b0f-45af-a16d-0a131b342f18)
高度上只有虚影像素的区别，长度上完全一致。
可能是音量图标除了喇叭口整体显得比较扁小所致。
播放顺序图标改动的话就不好看了，语言编写的图标，而且得考虑多DPI适应，请忽略像素级得差别。

**Comment by yiiyahui** [comment]
好吧。应该是高度导致视觉差异。
感谢！

**Comment by WhiteCoffee9834** [comment]
当你使用 WASAPI 的时候,你暂停,其他程序仍然不能播放声音,这时候停止跟暂停的区别就来了
