### ISSUE TITLE
ESLyric字体大小无法保存

### ISSUE THREAD

**Issue by ausar47** [dream7180/foobox-cn#203]
其它选项改了都会保存，就字号改了之后手动换个曲子又会变大

**Comment by dream7180** [comment]
没明白您的意思，哪里又会变大，foobox是不管理esl的字体大小的，esl字体的大小是跟随dui设置或者esl的面板参数自定义。

**Comment by ausar47** [comment]
![image](https://github.com/dream7180/foobox-cn/assets/73766358/4bd4d3bd-f18c-47bb-b35b-b031d093d60b)
一开始的大小
![image](https://github.com/dream7180/foobox-cn/assets/73766358/fbb12172-ff85-4656-bb8f-227e238d75a8)
修改字体大小
![image](https://github.com/dream7180/foobox-cn/assets/73766358/e22d5ba5-ad21-497f-a8e8-488a12db6195)
改成功了
![image](https://github.com/dream7180/foobox-cn/assets/73766358/64cb1455-e9c6-4fab-b3d1-bc9f7b8cd90b)
点击播放另一首歌，字体大小又变回来了

除了字体大小，其它比如字体、显示模式、对齐，改了之后都能始终保存

**Comment by a1waysbeta** [comment]
你应该是第一首歌曲有参照行，即翻译，第二首没有了，然后字体自动填充满桌面格子，变大了

**Comment by ausar47** [comment]
> 你应该是第一首歌曲有参照行，即翻译，第二首没有了，然后字体自动填充满桌面格子，变大了，换成双行显示就可以了！[ESLyric/feedback#85](https://github.com/ESLyric/feedback/issues/85)
还真是这样，感谢！解决了
