### ISSUE TITLE
7.9 版本的移除无效项不起作用了

### ISSUE THREAD

**Issue by 7peanuts** [dream7180/foobox-cn#208]
移除无效项不起作用了
移除重复项还是可以的

不知道是不是我安装的中文版本问题，请大佬测试一下。

顺便问一下，如何分隔识别多个艺术家，目前用 `;` 分隔的艺术家，还是只显示为一个整体。

**Comment by dream7180** [comment]
2.0汉化的中文变化了...下次更新修正一下。
分隔识别多个艺术家foobar2000原生不支持，不打算弄这个，因为播放列表里只能归入一个分组，分开识别那得归谁。

**Comment by 7peanuts** [comment]
> 分隔识别多个艺术家foobar2000原生不支持，不打算弄这个，因为播放列表里只能归入一个分组，分开识别那得归谁。

啊，我搞错了，或者说我描述错了，我想的是这种多人合作的音乐，能出现在每个艺术家的列表里就行。

现在用分号分隔 `艺术家A; 艺术家B`，每个艺术家是都能被识别到的，这首歌也会归属于每个艺术家。

虽然显示还是一个整体，但其实差别不大 😂

**Comment by 7peanuts** [comment]
> > 分隔识别多个艺术家foobar2000原生不支持，不打算弄这个，因为播放列表里只能归入一个分组，分开识别那得归谁。
> 
> 现在用分号分隔 `艺术家A; 艺术家B`，每个艺术家是都能被识别到的，这首歌也会归属于每个艺术家。
> 
> 虽然显示还是一个整体，但其实差别不大，坏处就是艺术家列表里看上去很乱 😂

想了下不对，现在这种歌曲是出现在多个艺术家名称整体的列表下面

我在贴吧看到个帖子，不知道说的对不对
https://tieba.baidu.com/p/6416173829
`在字段上加上 <> 符号 才能按照2个不同艺术家分类 例如 <%ARTIST%>`

**Comment by dream7180** [comment]
我的意思不是指封面浏览器，而是播放列表里，一首歌曲只能列出一条，播放列表也是可以分组的，当我以艺术家分组的时候，列在哪个艺术家名下好呢？不合适啊。

**Comment by 7peanuts** [comment]
> 播放列表也是可以分组的，当我以艺术家分组的时候，列在哪个艺术家名下好呢？不合适啊。

是不是封面浏览器里艺术家一经改动分开显示后，播放列表里的艺术家也会随之改变？
那能不能不改动播放列表，让它保持现在的格式 😆

**Comment by dream7180** [comment]
> > 播放列表也是可以分组的，当我以艺术家分组的时候，列在哪个艺术家名下好呢？不合适啊。
> 
> 是不是封面浏览器里艺术家一经改动分开显示后，播放列表里的艺术家也会随之改变？ 那能不能不改动播放列表，让它保持现在的格式 😆

不是随之改变，但最好统一，既然不能完全支持，就放弃吧😆
