### ISSUE TITLE
反馈一下遇到的问题

### ISSUE THREAD

**Issue by leafeg** [dream7180/foobox-cn#209]
用了好长时间FB2k，这款配置集是最喜欢的一款了。感谢开发者们的付出，在使用中发现了一些问题，反馈一下，希望能做的越来越好。

不知道是播放器本身的设定还是皮肤配置的问题，播放模式选择“随机”的时候，按”上一曲“播放就停止，只有“下一曲“有用。
希望能修复这个问题。

另外有个小建议，播放列表滚动条在鼠标经过的时候会变宽，以方便拖动。设计的很好，如果能增加一个淡入淡出的话体验会更好。

最后，再次感谢大佬给大家带来了这个配置集！

**Comment by dream7180** [comment]
1.随机只能下一首，这是foobar2000的设定，你可以选乱序，这样就可以上一首了。
2.淡入淡出我试试，效果不错的话7.10会加入。
谢谢！
