### ISSUE TITLE
使用智享阁的最新2.0版64位不生效

### ISSUE THREAD

**Issue by cocochinoa** [dream7180/foobox-cn#210]
![Uploading Snipaste_2023-06-20_14-35-10.png…]()

**Comment by dream7180** [comment]
说明里不是说了么，由于所依赖的组件 JSplitter 目前只有 32 位，故暂不支持 foobar2000 x64 版本。

**Comment by cocochinoa** [comment]
很抱歉，我没有仔细阅读说明。在我提出问题后我看到了说明，但没有回复你。这是我的过失。

dreamawake ***@***.***> 于 2023年6月20日周二 16:37写道：

**Comment by dream7180** [comment]
愿64位早日到来....

**Comment by smdx** [comment]
> 说明里不是说了么，由于所依赖的组件 JSplitter 目前只有 32 位，故暂不支持 foobar2000 x64 版本。

是脚本插件吗？看贴吧有人说官方论坛出了个支持64位版本的foo_jscript_panel3脚本插件
