### ISSUE TITLE
是否可以优化一下取色

### ISSUE THREAD

**Issue by IzayoiAster** [dream7180/foobox-cn#217]
比如这个封面，取色后字就看不清了
![image](https://cdn.staticaly.com/gh/IzayoiAster/-@master/Other/image.7i91q66hm340.webp)

**Comment by dream7180** [comment]
谢谢反馈，试试看，原来是已经优化取舍过的，要保留原味又要分辨率高很难十全十美

**Comment by charles7580** [comment]
请问如何关闭界面自动取色呢？有时候会影响到全屏歌词，降低辨识度，感恩！

**Comment by charles7580** [comment]
> 谢谢反馈，试试看，原来是已经优化取舍过的，要保留原味又要分辨率高很难十全十美

请问如何关闭界面自动取色呢？有时候会影响到全屏歌词，降低辨识度，感恩！

**Comment by IzayoiAster** [comment]
> > 谢谢反馈，试试看，原来是已经优化取舍过的，要保留原味又要分辨率高很难十全十美
> 
> 请问如何关闭界面自动取色呢？有时候会影响到全屏歌词，降低辨识度，感恩！

关闭foobox设置里的高亮色跟随封面颜色 @charles7580
