### ISSUE TITLE
”喜爱“按钮消失

### ISSUE THREAD

**Issue by su497776915** [dream7180/foobox-cn#220]
记得之前版本在评星旁边能打标签添加入喜爱的音轨的
这个版本的按钮消失了，但是之前加入的播放列表还存在
能不能恢复这个按钮
![Snipaste_2023-08-24_22-21-59](https://github.com/dream7180/foobox-cn/assets/17957030/44d2f8ec-d7e2-4a8b-8f36-4781eb79abc4)

**Comment by dream7180** [comment]
在那里右键菜单里可选的

**Comment by su497776915** [comment]
> 在那里右键菜单里可选的

找到了感谢
