### ISSUE TITLE
7.12 调整列的顺序无法保存

### ISSUE THREAD

**Issue by zzyy21** [dream7180/foobox-cn#222]
在7.12中按照自己的习惯调整列的排序，关闭后重新打开会恢复成固定的顺序

例如勾选并调整顺序为：索引，状态，标题，艺术家，#，时间
重启后顺序会变为编辑列中的固定顺序：状态，索引，#，标题，艺术家，时间

**Comment by dream7180** [comment]
顺序应该是我忽略了，谢谢指出！
