### ISSUE TITLE
右键点击歌曲不能发送到其他播放列表，以前旧版可以的

### ISSUE THREAD

**Issue by klxq520** [dream7180/foobox-cn#225]
右键点击歌曲不能发送到其他播放列表，以前旧版可以的，还是我操作的不对啊

**Comment by dream7180** [comment]
没问题的啊，你是怎么操作的？

**Comment by klxq520** [comment]
> 没问题的啊，你是怎么操作的？

搞定了，在设置里开启就行，以前是默认显示的，现在新版默认不显示
