### ISSUE TITLE
歌曲封面下的评级显示不能实时同步

### ISSUE THREAD

**Issue by Sora98** [dream7180/foobox-cn#226]
![image](https://github.com/dream7180/foobox-cn/assets/49893890/afc3562b-bf50-4ed6-b0c9-df76751267aa)
如图，已经点了5星，但是右侧依然为空，必需切到别的歌曲播放然后再切回来才能更新显示，所有歌曲都是如此，求解决

**Comment by dream7180** [comment]
嗯，谢谢反馈，不小心引入的bug，下个更新更正
