### ISSUE TITLE
深色模式下附加行信息在选中时字体颜色未改变

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#228]
如题，浅色模式下附加行信息在选中时会和主行信息一起变为白色，但深色模式下颜色不会改变，导致一些情况下没法看清附加行的内容，希望能修正

**Comment by Ptilopsis01** [comment]
> 如题，浅色模式下附加行信息在选中时会和主行信息一起变为白色，但深色模式下颜色不会改变，导致一些情况下没法看清附加行的内容，希望能修正

更正一下，不是选中时而是播放时

**Comment by dream7180** [comment]
谢谢反馈，下个更新修正
