### ISSUE TITLE
[Feature Request]: 希望能增加播放列表隐藏（收起）/显示功能及按钮

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#229]
可能要求有点高，希望能增加一个按钮让可控制播放列表的显示/隐藏状态，类似于
![image](https://github.com/dream7180/foobox-cn/assets/93318731/f926d71c-c356-4069-a5c9-89dc62f5fcec)
![image](https://github.com/dream7180/foobox-cn/assets/93318731/a38ca104-e93f-493b-9c05-a974c19ca263)
或者在隐藏时减小窗口横向尺寸，显示时再扩大窗口横向尺寸

**Comment by dream7180** [comment]
使用DUI分离器，除非同一面板内建，否则实现不了。暂不考虑此方向。
可以把面板拉小到只剩分隔条。
