### ISSUE TITLE
[Feature Request]: 附加行中同时显示专辑艺术家和音轨艺术家

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#233]
如题，现在附加行有专辑艺术家就会只显示专辑艺术家而不显示音轨艺术家，但专辑艺术家有时是某公司或作品名而不是具体的作者，希望两者能同时显示，比如“专辑艺术家/音轨艺术家”这样

**Comment by dream7180** [comment]
但更多时候这样显示会很多余哦

**Comment by Ptilopsis01** [comment]
> 但更多时候这样显示会很多余哦

能做成可选项吗，因为我有很多作品都是专辑艺术家并非作者的，只显示专辑艺术家有点难受

**Comment by dream7180** [comment]
您可以自己改一下代码

**Comment by Ptilopsis01** [comment]
> 您可以自己改一下代码

请问是在哪个js里，找半天没找到（）

**Comment by Ptilopsis01** [comment]
没事了，我找到怎么改了（）
