### ISSUE TITLE
自动下载封面的插件还有吗？如果没有的话，去哪里下载封面更方便

### ISSUE THREAD

**Issue by WnXdb** [dream7180/foobox-cn#235]

**Comment by dream7180** [comment]
Musictag，可以在foobox调用

**Comment by WnXdb** [comment]
> Musictag，可以在foobox调用

为啥我的没有这个选项啊
![image](https://github.com/dream7180/foobox-cn/assets/59195609/98826ead-46de-4a9e-b307-ec957d95f711)

**Comment by dream7180** [comment]
在 foobox 设置--播放列表视图里设置
![mtag](https://github.com/dream7180/foobox-cn/assets/18242221/21141a98-7a51-47cc-9f8e-0d65bafa1b94)
