### ISSUE TITLE
最新版（7.16 20231119）的深色模式问题

### ISSUE THREAD

**Issue by got233** [dream7180/foobox-cn#237]
![屏幕截图 2023-11-25 204250](https://github.com/dream7180/foobox-cn/assets/40763801/a3602026-8a68-473b-8bd5-fffba8f4990e)
如图，忘记是从哪个版本升上来的，结果升级之后发现深色模式的文本都是黑色，整个页面黑乎乎的。
很喜欢原来的深色模式，不知道有什么办法可以恢复。

**Comment by dream7180** [comment]
先在参数选项里选择深色模式，如图：
![图片](https://github.com/dream7180/foobox-cn/assets/18242221/95a79f29-622e-4ddc-8296-dda9024e4c07)
