### ISSUE TITLE
请问release中可以提供原本单独的组件吗

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#238]
如题，因为我是使用别的整合安装再单独添加foobox的，如果和原来一样有foobox组件独立的打包会方便很多

**Comment by dream7180** [comment]
您可以便携安装再自行提取一下....

**Comment by Ptilopsis01** [comment]
> 覆盖应该没什么问题，您也可以便携安装再自行提取一下....

用7z也可以从安装程序中直接拆出需要的组件，不过我还是觉得有单独的组件打包会比较好（）

**Comment by dream7180** [comment]
嗯，我也是被人追安装包，自从加入了简介面板和foo_youtube后，绿色就解决不了问题，所以才搞了安装包，其实你覆盖是无害的，我的更新还是很快的。
