### ISSUE TITLE
可以增加一个保存修改时间轴后的歌词的选项吗

### ISSUE THREAD

**Issue by github-24** [dream7180/foobox-cn#239]
怎么复制保存都是原来时间轴的歌词，调整偏移后的复制不了

**Comment by dream7180** [comment]
这个得向ESLyric的作者反馈，我帮你反馈一下

**Comment by github-24** [comment]
> 这个得向ESLyric的作者反馈，我帮你反馈一下

谢谢

**Comment by dream7180** [comment]
偏移只是歌词文本开头加个offset值就能实现，并非修改时间标签，所以没办法的。
