### ISSUE TITLE
v 7.17无法播放.dsf文件了

### ISSUE THREAD

**Issue by IzayoiAster** [dream7180/foobox-cn#241]
相同的文件之前的版本都可以播放。
为了避免是因为新版本更换为了安装程序导致漏安装，我又重新安装了一般，确认勾选了高级输出组件。
![](https://github.com/IzayoiAster/-/raw/master/Other/image.26hmz7uy5s8w.webp)

**Comment by github-24** [comment]
我也是这样

**Comment by dream7180** [comment]
安装时额外解码器--DSD/SACD解码组件选了吗

**Comment by github-24** [comment]
> 安装时附加解码器--DSD/SACD解码组件选了吗

确实没勾选，还以为黑色的勾是默认选了

**Comment by IzayoiAster** [comment]
> 安装时额外解码器--DSD/SACD解码组件选了吗

原来是这样。印象里大多安装程序里“⬛”是半选，“✔”是全选，我还以为已经全选了😂
