### ISSUE TITLE
面板属性里的 边缘样式 和 仿真透明 效果为什么修改无效？

### ISSUE THREAD

**Issue by yaotosehinako** [dream7180/foobox-cn#243]
怎么设置成像其他人的这种 边框是 圆角加彩色的？
其他人设置的：
![01](https://github.com/dream7180/foobox-cn/assets/103052436/2fb25651-a046-4318-89da-0cb8673fbd07)
这是我自己的设置，为什么无效？
![02](https://github.com/dream7180/foobox-cn/assets/103052436/02ba8277-a635-4a75-b355-a76c2165233e)
实在搞不懂原因，还望答疑解惑。

**Comment by yiiyahui** [comment]
上：windows 11
下：windows 10

**Comment by yaotosehinako** [comment]
> 上：Windows 11 下：Windows 10

感谢解惑！不知是什么参数导致的，可有解决方法吗？

**Comment by dream7180** [comment]
这是windows界面的事，不是面板的界面，得装win11
