### ISSUE TITLE
开机首次打开慢，关闭会弹崩溃弹窗与网页

### ISSUE THREAD

**Issue by goeway** [dream7180/foobox-cn#246]
下的应该是2.1+7.18的整合包，
开机首次打开很慢，
感觉要三四秒左右，
比现在用的1.6.16整合包要慢不少，
感觉很明显。
关闭时常会弹出崩溃窗口与汉化提供者的网站页面

系统是win10家庭版 22H2，内存16G，CPU 8代i5
![2024-01-05_214826](https://github.com/dream7180/foobox-cn/assets/23276757/33363c5f-74a8-486c-9247-ef7d61a8f938)

**Comment by yiiyahui** [comment]
打开慢两种可能，一是硬盘，二是windows自带的反病毒，影响所有软件的打开速度，如图，关闭它有惊喜。

崩溃就不晓得了，还是直接用原版，毕竟非官方汉化
![Screenshot](https://github.com/dream7180/foobox-cn/assets/30188835/51d73cfe-05dd-48b4-8c78-89784104ad52)

**Comment by dream7180** [comment]
7.20应该解决崩溃问题，是简介面板脚本引起。
