### ISSUE TITLE
升级配置保存问题

### ISSUE THREAD

**Issue by YooHole** [dream7180/foobox-cn#25]
更新版本后，都是初始化了，需要重新配置显示设置什么的。 能怎样解决吗？

**Comment by iamdicer** [comment]
我这也是一样的问题，本来调整了很久，更新一下全没了😂

**Comment by Nanlon** [comment]
使用下面这个安装包，安装配置好后，下次新版本安装或覆盖安装时有个升级模式，直接覆盖就行，保留配置。
https://github.com/Nanlon/foobox-cn/releases/download/6.1.5.3/Foobox_6.1.5.3.zip

**Comment by ForsakenRei** [comment]
我丢了播放列表，还好有备份

**Comment by SplitGemini** [comment]
+1，全丢了

**Comment by shardine** [comment]
把根目录下的configuration文件夹导出，然后替换更新后的configuration

**Comment by shardine** [comment]
@dream7180 这好像是安装程序的逻辑问题，更新的时候不会保留原有的配置文件，希望作者能修改一下，感谢
