### ISSUE TITLE
v7.20无法拖拽歌曲到播放列表

### ISSUE THREAD

**Issue by mengx8** [dream7180/foobox-cn#250]
之前用的都是foobox_6.x
更新到最新版后，发现拖拽不能用了

如图，拖拽歌曲或文件夹都不行，之前老版本是可以的
我是win10系统64位，尝试对程序使用以管理员身份启动，还是不行

![e2f814c6f321af4367af7a3f2e9e342](https://github.com/dream7180/foobox-cn/assets/16496935/4f4f08d5-f466-484d-8dfb-edd1ff16d310)
![fabe7db9574f4fe2197a52f2d6825a2](https://github.com/dream7180/foobox-cn/assets/16496935/4a664a31-0675-4ce2-8554-470ebf5c1303)

**Comment by dream7180** [comment]
未发现有问题，你注意看看不要往智能列表里拖

**Comment by czrae** [comment]
我也不能拖拽

**Comment by Masir01** [comment]
别用管理员模式应该可以, 用管理员模式好像不行了就
