### ISSUE TITLE
7.20播放tak文件会崩溃。

### ISSUE THREAD

**Issue by Oldkun** [dream7180/foobox-cn#251]
之前版本foobox装foo_input_tak插件没有这个问题，汉化版2.1装插件也没问题。7.20foobox装不装插件一点播放就崩溃。

**Comment by dream7180** [comment]
foobar2000 说原生支持的，我试过没问题，你试试新版本？

**Comment by debutow** [comment]
> foobar2000 说原生支持的，我试过没问题，你试试新版本？

作者您好，7.23（完整安装 便携模式，系统win10pro 22H2 19045.4046）播放某些tak仍然会崩溃😂
（会崩溃的tak文件）https://wwt.lanzoul.com/i1QgE1q8rlla
