### ISSUE TITLE
请问能否直接解压安装？

### ISSUE THREAD

**Issue by erikaemma** [dream7180/foobox-cn#253]
我发现直接运行需要管理员权限，所以我打算改后缀名为rar然后直接用bandizip解压后运行，请问是否可以？

**Comment by dream7180** [comment]
不行的，因为打包兼顾了便携与系统安装。我下个版本尝试一下打个不需要管理员权限的包的版本（一些注册组件和改lastfm hosts的操作需要管理员权限）

**Comment by dream7180** [comment]
7.24将不含foobar2000，不需管理员
