### ISSUE TITLE
声频点击右键foobar立即崩溃

### ISSUE THREAD

**Issue by yuki6761** [dream7180/foobox-cn#255]
版本v7.21

![image](https://github.com/dream7180/foobox-cn/assets/26682787/b3f7f51f-1416-4acb-afec-5eec47479990)
![image](https://github.com/dream7180/foobox-cn/assets/26682787/1c1ebaed-54bb-4283-b809-21f4244797f4)

**Comment by asky88** [comment]
[failure_00000002.dmp](https://github.com/dream7180/foobox-cn/files/14329008/failure_00000002.dmp)
[failure_00000002.txt](https://github.com/dream7180/foobox-cn/files/14329009/failure_00000002.txt)
遇到相同问题，上面是Log

**Comment by a1waysbeta** [comment]
汉化版更新了，群里下载覆盖一下就可以了
