### ISSUE TITLE
关于添加"最喜爱"播放列表

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#256]
头一次使用favorite播放列表
发现假如先添加A专辑的曲目到到"最喜爱"播放列表，接着添加B专辑某曲目，然后再添加A专辑的某曲目
此时从A专辑第二次添加的不会在先前A的栏目里，而是另起一个。能使相同专辑添加的曲目都在一起吗？
![s](https://github.com/dream7180/foobox-cn/assets/30188835/906d2166-31ac-4a50-bc58-8d4fdebda44f)

**Comment by a1waysbeta** [comment]
手动按专辑排序一下

**Comment by yiiyahui** [comment]
> 手动按专辑排序一下

手动是可以，3Q
