### ISSUE TITLE
[Feature Request]: 封面浏览器界面中可设置按媒体库文件夹结构获取封面

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#260]
如题，目前封面浏览器只能获取音频文件中的封面，如果能做成像ecn的媒体库那样按照文件夹获取媒体库中的封面就好了

**Comment by dream7180** [comment]
面板左上角有切换按钮

**Comment by Ptilopsis01** [comment]
确实哦，视图里可以设置成文件夹，但它显示的是音频文件所在的文件夹
ecn那个它是显示的媒体库下的一级子文件夹，不知道能不能增加这个功能

**Comment by dream7180** [comment]
那个是libtree...，好吧，下个版本我会添加一个媒体库一级目录的分组。

**Comment by Ptilopsis01** [comment]
> 那个是libtree...，好吧，下个版本我会添加一个媒体库一级目录的分组。

不好意思描述的不是很清楚
非常感谢
