### ISSUE TITLE
为什么我添加进去的cue文件，打开音乐后会显示“找不到对象”？

### ISSUE THREAD

**Issue by achieve123** [dream7180/foobox-cn#261]
如图，cue文件可以正常显示，但是找不到对象，用其他软件如potplayer可以找到
![PixPin_2024-02-24_13-55-48](https://github.com/dream7180/foobox-cn/assets/105585157/ed4f3e7c-d4ea-4846-a2e6-51fad1ff914e)
![PixPin_2024-02-24_13-54-13](https://github.com/dream7180/foobox-cn/assets/105585157/2b291f03-9087-403c-89f7-2c49c9694adc)
![PixPin_2024-02-24_13-54-59](https://github.com/dream7180/foobox-cn/assets/105585157/d0a999e2-fc3e-4876-b50b-6a1da0bd79cf)

**Comment by tuwulin365** [comment]
cue文件有问题，这一行文件名不对。我用pot也没法播啊。
FILE "[葉惠美].flac" WAVE
