### ISSUE TITLE
关于字体渲染.........

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#263]
突然发现歌词插件面板可以调整字体渲染为directwrite，如图(放大)

![1](https://github.com/dream7180/foobox-cn/assets/30188835/87a9e623-1b22-4efd-96bf-7c83804573b2)

那面板可以做到吗？以下是面板的cleartype(放大)

![2](https://github.com/dream7180/foobox-cn/assets/30188835/ffa2a0cb-0d3b-4c35-9c36-ccbe294afa0f)

**Comment by a1waysbeta** [comment]
目前不可以

**Comment by yiiyahui** [comment]
> 目前不可以

那可惜了。感谢回复！
