### ISSUE TITLE
foobox內置轉換器有錯誤，m4a轉換會造成歌曲卡頓！

### ISSUE THREAD

**Issue by mazakanull1** [dream7180/foobox-cn#267]
2021-2023我收集歌曲，下載了一萬多首歌，其中約一半都用foobox內置的轉碼器轉換過。96kbps M4a格式。結果目前聽約15%的歌曲都有卡頓，也就是兩三千首歌曲。還在苦苦尋找中，給我造成巨大的精神損失。我立誓再也不用中國產軟體了

**Comment by mazakanull1** [comment]
目前只能慢慢替換錯誤的音頻了。聽一首，發現出現問題，記録。預計半年內聽完所有歌曲並找出所有有毛病的歌曲，逐一替換。
非常的讓我生氣

**Comment by tuwulin365** [comment]
也可能是源文件有问题。
还有，96k也太暴殄天物了吧，至少256k呗。

**Comment by dream7180** [comment]
foobar2000 和转换组件都不是我生产咯，有问题可反馈到 QAAC 项目，如果是用 qaac 转的话。
