### ISSUE TITLE
未找到“专辑封面以碟片优先”功能

### ISSUE THREAD

**Issue by NicodeSS** [dream7180/foobox-cn#271]
在5.7.0版(更新日志)[https://www.cnblogs.com/foobox/p/11492121.html]中提到的“专辑封面以碟片优先”功能并没有在foobox菜单中找到。是在高版本移除了么？如果是，现在还有方法实现相同的功能么？

**Comment by dream7180** [comment]
去除了该功能，除了改代码没什么方法，要么就手动把碟片封面转移到封面上
