### ISSUE TITLE
7.2.5版本在安装时选任何位置都是安装不了

### ISSUE THREAD

**Issue by ChandlerBBT** [dream7180/foobox-cn#272]
![image](https://github.com/dream7180/foobox-cn/assets/17948924/46d4d60b-2a63-44ff-936f-539d3e7684fe)

**Comment by ChandlerBBT** [comment]
![image](https://github.com/dream7180/foobox-cn/assets/17948924/db14397c-d4a8-4543-9815-f29cd470a388)

**Comment by yukino1111** [comment]
你要先装个foobar2000才行
