### ISSUE TITLE
有可能列表是以颜色间隔的吗？

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#273]
去掉灰色的列表分隔线，而是以背景色分隔。浅色模式下效果大约如下
![1](https://github.com/dream7180/foobox-cn/assets/30188835/0402a662-773f-485f-8a91-1ed5e580e58f)

如此顺便可以降低行高，目前列表文字与行高的比例大约是35%。如果调整比例约50%，则效果大约如下

![2](https://github.com/dream7180/foobox-cn/assets/30188835/bab4fbeb-fbfc-4676-a534-61f77b7de89f)

**Comment by dream7180** [comment]
不会采用这种配色。另外行高可以在面板属性那自行设定的。
