### ISSUE TITLE
能否对原版foobar2000提供支持？

### ISSUE THREAD

**Issue by Absolves** [dream7180/foobox-cn#274]
因为汉化版本更新较慢，加上我希望使用官方原版，因此我从官方下载了英文原版，同时迁移了Asion汉化版的插件（在此感谢译者）。安装皮肤后基本运行正常，但是有两个问题：
1.无法给歌曲评星，右侧封面下方的星星点击无反应，在放映列表处点击评星后，当失去鼠标焦点时评星会消失
2.最下方操作栏的打开文件按钮点击无反应
<img width="260" alt="image" src="https://github.com/dream7180/foobox-cn/assets/47398005/97e09f5f-9038-4e6a-858c-720d7ec025a4">

目前，在汉化版中暂未发现相关问题。请问作者能否对英文原版提供支持呢？谢谢！

**Comment by isolitude** [comment]
作者还有个foobox-en项目，可以去看看

**Comment by Absolves** [comment]
> 作者还有个foobox-en项目，可以去看看

非常感谢，已经更换到foobox-en
