### ISSUE TITLE
[已解决] AAC解码失败

### ISSUE THREAD

**Issue by User-Lambda** [dream7180/foobox-cn#275]
在使用Asion的汉化版+foobox将歌曲转换为AAC编码时会发生编码错误, 原因是缺少QtFiles, 8u已寻找出解决方案.
https://tieba.baidu.com/p/7017152152
https://github.com/AnimMouse/QTFiles
所以以后可以内置QtFiles吗?

**Comment by dream7180** [comment]
https://dream7180.github.io/2023/foobar2000-qaacenc/
