### ISSUE TITLE
能否关闭软件高亮色随专辑封面取色？会干扰桌面全屏歌词的高亮色

### ISSUE THREAD

**Issue by charles7580** [dream7180/foobox-cn#278]
如题，感谢。软件高亮色随专辑封面取色会覆盖桌面全屏歌词的高亮色。

**Comment by pencilq** [comment]
可以设置的，如下图：
![2024-05-13_103951--](https://github.com/dream7180/foobox-cn/assets/20763059/57aa5f89-4bac-4d17-9f3b-a91963a088e0)
建议把 radio 改为 checkbox 更直观易懂

**Comment by charles7580** [comment]
> 可以设置的，如下图： ![2024-05-13_103951--](https://private-user-images.githubusercontent.com/20763059/329906317-57aa5f89-4bac-4d17-9f3b-a91963a088e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NjkyMjYsIm5iZiI6MTcxNTU2ODkyNiwicGF0aCI6Ii8yMDc2MzA1OS8zMjk5MDYzMTctNTdhYTVmODktNGJhYy00ZDE3LTlmM2ItYTkxOTYzYTA4OGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDAyNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0YTAyNDNiZGVjYzZhZDQxMGE2OWRmMzZkNjczYjlkMjE5OTU4ZmQyNjJkNjQ5NTIyY2E1ZmJlODU3ZTQzNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nUHU7I1qujtgPdUEOmeLR7n21tSyI2QmN9iZSnMPux4) 建议把 radio 改为 checkbox 更直观易懂

感谢，不过您的这个版本是最新版本吗？我在旧版本能找到foobox设置的入口，但是新版本不知道在哪里

**Comment by pencilq** [comment]
右键 → foobox 设置

![2024-05-13_110552](https://github.com/dream7180/foobox-cn/assets/20763059/06eb1990-5738-4e0c-bce4-8402e5f06c5b)

**Comment by charles7580** [comment]
哈哈哈还蛮隐蔽的，感恩！
