### ISSUE TITLE
[BUG] 64位版本播放列表栏在筛选状态下选中时会自动大幅度向上滚动

### ISSUE THREAD

**Issue by Ptilopsis01** [dream7180/foobox-cn#279]
rt，在筛选栏输入内容对播放列表进行筛选后，如果选中下方的播放列表，会导致整个播放列表栏大幅度向上滑动，即使关闭触控模式也依然存在

**Comment by dream7180** [comment]
？哪个筛选栏？播放列表你选中最下方的项目（如果那一行行高显示不完整），会让它滚到面板中间的，一直都是这样。

**Comment by Ptilopsis01** [comment]
> ？哪个筛选栏？

就是播放列表上面那个搜索栏

> 播放列表你选中最下方的项目（如果那一行行高显示不完整），会让它滚到面板中间的，一直都是这样。

我怀疑是不是新版在筛选状态下对选中行的位置或者编号判断出问题了，因为我任意点一行都会大幅度往上滑

**Comment by dream7180** [comment]
好的，看到了，是我优化代码时忽略了，过几天更新修正，谢谢反馈
