### ISSUE TITLE
x64三个bug

### ISSUE THREAD

**Issue by yiiyahui** [dream7180/foobox-cn#286]
1：切换basic和blog布局会出现如下图，重启可恢复。且布局位置相关不会被保存，比如位置，大小宽度等等（记住）。切换后会被初始化。ps：在上个版本也有此问题。在win10下似乎不会。

![1](https://github.com/dream7180/foobox-cn/assets/30188835/6473d78c-8b16-4a0c-825e-056d8e58a9b7)

2：以下情况下播放列表拖动cover栏时会出现错误。已知视频里情况必复现：列表内有专辑为单曲--------当cover大小超过两行或两行以上，拖动cover大小至两行或以下时

https://github.com/dream7180/foobox-cn/assets/30188835/61c37756-791a-4586-9ea2-9e3dea0dbb34

3：在设置窗口下切换basic和blog并选中其中一个。不关闭设置窗口。此时点击控制栏的列表或浏览面板会崩潰。

![2](https://github.com/dream7180/foobox-cn/assets/30188835/1ea67b21-88b1-430d-8864-d38a4bf0b1f6)

**Comment by dream7180** [comment]
切换问题是jsp的问题，切换后如果不重启，要改变一下窗口大小才能加载（如最大化后恢复一下窗口）。
至于布局不能保存，这个是需要手动保存的，你可以在参数选项里自行导出覆盖或另存为其他布局，这样就能建立自己需要的布局了。
第二个问题谢谢反馈，我有空还原一下问题检查代码。

**Comment by yiiyahui** [comment]
> 切换问题是jsp的问题，切换后如果不重启，要改变一下窗口大小才能加载（如最大化后恢复一下窗口）。 至于布局不能保存，这个是需要手动保存的，你可以在参数选项里自行导出覆盖或另存为其他布局，这样就能建立自己需要的布局了。 第二个问题谢谢反馈，我有空还原一下问题检查代码。

谢谢，更新了下，第3个图里的问题还在。。感觉还是用着不如x86的感觉。。现在是列表多出一行了。。强迫症暂时退回x86了。总感觉这个x64面板插件有问题。

**Comment by dream7180** [comment]
图3的问题已经回答过了：切换布局后如果不重启，要改变一下窗口大小才能加载（如最大化后恢复一下窗口）。
另x86和x64的列表都是一样的。不知道您说的多一行是什么情况。
