### ISSUE TITLE
7.27+asion 2.15 X64面板无法保存评级.

### ISSUE THREAD

**Issue by lisansas** [dream7180/foobox-cn#288]
开启foobox设置写入文件标签.

此时无论在面板上点任何评级都无法保存,用右键播放统计信息+评级则可以保存也可以显示

**Comment by dream7180** [comment]
请使用Asion汉化版里的播放统计组件，有些组件其他人汉化的用词不一样

**Comment by dream7180** [comment]
额...在我的集成里，得换一下
