### ISSUE TITLE
歌曲等级设置无效

### ISSUE THREAD

**Issue by qiuhlee** [dream7180/foobox-cn#290]
![21469](https://github.com/dream7180/foobox-cn/assets/150875954/b600835b-db37-4637-9a5e-21d1f64bfa87)
foobar2000版本： v2.1.5 [x64]
foobox版本： [v7.28]

**Comment by dream7180** [comment]
请使用Asion汉化版，别人翻译的命令有所不同

**Comment by qiuhlee** [comment]
多谢大神，问题已解决
