### ISSUE TITLE
[BUG] 每次通过安装包覆盖更新后界面布局及插件设置丢失

### ISSUE THREAD

**Issue by Xionghaizi001** [dream7180/foobox-cn#291]
## 发生了什么？
通过安装包覆盖更新后，界面内一片空白，什么组件都没有。并且一些插件（如ESlyric）设置丢失（也可能没有丢失，但它工作不正常）

## 怎么发生的？
下载安装包→点击打开→选择之前版本安装的位置→安装→打开软件

## 预期效果？
正常显示界面组件

## 补充信息
![image](https://github.com/dream7180/foobox-cn/assets/50747104/5780df0c-d3f8-4bfe-9442-5932fe96d175)

**Comment by dream7180** [comment]
theme.fth文件没更新到？也不应该出现这样的界面的。至于ESL设置，foobox并不会动它，不带的，只是更新组件版本

**Comment by Xionghaizi001** [comment]
> theme.fth文件没更新到？也不应该出现这样的界面的。至于ESL设置，foobox并不会动它，不带的，只是更新组件版本

。忘关这个issue了， 更新一下fb2k版本以后就正常了
