### ISSUE TITLE
7.30 版本x86及x64都会百分百复现此问题

### ISSUE THREAD

**Issue by CodingRookie98** [dream7180/foobox-cn#294]
![image](https://github.com/user-attachments/assets/3e84f36f-abde-49de-9ff1-8a782054c4d3)
无论完全卸载重装还是按照还是按照作者给的操作都不能解决

**Comment by CodingRookie98** [comment]
另外foobar2000版本为v2.1.5 Asion汉化版

**Comment by CodingRookie98** [comment]
![image](https://github.com/user-attachments/assets/6ab07796-0eb6-4143-b2e6-16f9f9742561)
`function on_init() {
	window.DlgCode = DLGC_WANTALLKEYS;
	if (!utils.IsDirectory(fb.ProfilePath + "foobox\\config")) {
		var fso = new ActiveXObject("Scripting.FileSystemObject"); 
		fso.CreateFolder(fb.ProfilePath + "foobox\\config"); 
	}`
出错代码位置，不懂js，手动解决的办法是在安装目录foobar2000\profile\foobox新建config目录可解决

**Comment by CodingRookie98** [comment]
Failed to create ActiveXObject object via CLSID: WScript.Shell

文件: jsspm.js
行: 194, 列: 17
堆栈跟踪:
  get_windows_version@jsspm.js:194:17
  htmlCode@jsspm.js:181:38
  HtmlDialog@jsspm.js:173:34
  DeletePlaylist@jsspm.js:169:12
  oBrowser/this.context_menu@jsspm.js:1151:20
  oBrowser/this.on_mouse@jsspm.js:742:14
  on_mouse_rbtn_up@jsspm.js:1421:7
![image](https://github.com/user-attachments/assets/88a733cb-cfe7-4a0e-8dcc-470f25349a38)
还是ActiveXObject控件的问题

**Comment by CodingRookie98** [comment]
好像是因为IE从Win11系统被彻底移除，连微软自家的Edge都放弃ActiveX了，难崩.............

**Comment by dream7180** [comment]
11应该还是支持activex的吧，你的系统是不是优化过头的那种？我也尽量不适用activex，但建立文件夹之类一些操作还是得调用它.

**Comment by CodingRookie98** [comment]
已解决
