### ISSUE TITLE
此版本播放 .rar 中的 .wav 时 CPU 占用率过高 

### ISSUE THREAD

**Issue by moonvoidpro** [dream7180/foobox-cn#3]
用 git 版（foobox 6.2019.08-git）客户端播放 .rar （非加密）中的 .wav 文件时，cpu 占用率会稳定超过 80%，而同样的压缩包同样的音频文件用 foobar 2000 Windows 商店版（v1.4.6）播放则不用 5%。

本人平台：win10 1903 18362.295；CPU i5-6200U；内存 8 GB。下载安装后未更改任何设置。

**Comment by klxq520** [comment]
播放压缩包这种功能就不应该出现，先不说程序要经过一个解压过程不说，对于音乐管理也造成很多不便，我以前所有的压缩包都直接解压了，管理起来好麻烦，而且音乐的压缩并没有节省很多空间
