### ISSUE TITLE
最新这版太卡了，直接就是无响应

### ISSUE THREAD

**Issue by yufeilai666** [dream7180/foobox-cn#300]
![image](https://github.com/user-attachments/assets/33e2ce66-65bc-4580-93f6-b275b1716948)
最新这版太卡了，直接就是无响应，或者播放有声音但是界面直接卡死，媒体库6000首歌。

版本	Windows 10 专业版
版本号	22H2
操作系统内部版本	19045.4412
体验	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by yufeilai666** [comment]
打开软件自动播放上次关闭时的进度，页面加载不完全并且卡主，但有声音。

https://github.com/user-attachments/assets/0d71af7e-ae87-46d7-9036-b72f46f598c2

**Comment by dream7180** [comment]
第一次打开简介初始化可能会卡一下，以后打开应该没事，实在不行就切换成没简介的布局

**Comment by yufeilai666** [comment]
> 第一次打开简介初始化可能会卡一下，以后打开应该没事，实在不行就切换成没简介的布局

去掉简介面板也是一样非常卡，就算暂停播放音乐，滑动列表也是很卡。

https://github.com/user-attachments/assets/44177844-1598-468e-8816-e45d19fcdb1e

**Comment by yufeilai666** [comment]
> 第一次打开简介初始化可能会卡一下，以后打开应该没事，实在不行就切换成没简介的布局

卸掉旧的foobar2000和foobox，全新安装后，直接打开使用就会直接卡死。切换布局成foobox基础，然后再切换成foobox基础+简介，重启电脑后就变正常不卡了。

**Comment by yufeilai666** [comment]
> > 第一次打开简介初始化可能会卡一下，以后打开应该没事，实在不行就切换成没简介的布局
> 
> 卸掉旧的foobar2000和foobox，全新安装后，直接打开使用就会直接卡死。切换布局成foobox基础，然后再切换成foobox基础+简介，重启电脑后就变正常不卡了。

话说早了，又复发了。

**Comment by dream7180** [comment]
用非foobox的主题不卡么？这方面是个例，其他人几万曲目也没有这情况

**Comment by yufeilai666** [comment]
> 用非foobox的主题不卡么？这方面是个例，其他人几万曲目也没有这情况

我现在用foobox7.25，也就是最后一版不区分x64的那个，一点也不卡。

**Comment by marcuccilli** [comment]
我是直接切换布局到任意一个别的再切回来就不卡了，不然巨卡无比
