### ISSUE TITLE
foobox设置页，电台地址无法更换

### ISSUE THREAD

**Issue by yufeilai666** [dream7180/foobox-cn#303]
foobox设置页，电台地址无法更换，修改后无法生效，重启后又变成默认的了。
![image](https://github.com/user-attachments/assets/6871466c-09f0-48db-95f0-62af74346080)

**Comment by dream7180** [comment]
不会啊，输入后回车，输入后需回车

**Comment by yufeilai666** [comment]
> 不会啊，输入后回车，输入后需回车

原来这样，确实可以了。
