### ISSUE TITLE
右键添加播放队列后建立的播放队列会崩溃消失

### ISSUE THREAD

**Issue by HikariNia** [dream7180/foobox-cn#307]
从媒体库中选择歌曲，右键添加到播放队列，之后选择添加完毕的播放队列开始播放的话，会弹出以下错误，并且播放队列崩溃消失。
![image](https://github.com/user-attachments/assets/4d1d8681-e97e-479e-bef5-6d8d00dd3037)

![image](https://github.com/user-attachments/assets/53eb3202-58ab-4947-9a59-de9927320310)

**Comment by dream7180** [comment]
谢谢反馈，播放队列列表消失是应该的，因为手动播放会清空先前建立的播放队列。下个版本会修正崩溃问题。

**Comment by HikariNia** [comment]
感谢！
不过关于播放队列我不是很理解。比如说我现在通过在媒体库中右键"添加到播放列表"建立了如图的播放队列
![image](https://github.com/user-attachments/assets/40485eb4-2dc9-4262-9ddf-dbcc56585d1e)
现在如果我想播放这个创建好的队列，如果双击播放队列
![image](https://github.com/user-attachments/assets/0617707e-d14d-47f6-90bc-70b0ade24af5)
那么接下来队列会消失，队列中的第一首歌会被播放，但是当第一首歌播放完之后就会停下来，队列中的其他歌曲都不会被播放。
如果当前已经有正在播放的歌曲，那么下一首会按照播放队列顺序直到播放队列完成。
也就是说播放队列不能主动开始吗？只能用下一首按钮来触发？

**Comment by dream7180** [comment]
是的，foobar2000 的设定就是这样，合情合理，点下一首按钮会按既定顺序播放，但手动点任意一首则会清空当前队列。你点播放队列列表第一首和点别的播放列表别的歌曲效果是一样的（这个播放列表队列其实是不应该存在的， 它是由foobox 脚本创建的，原版不能显示这个列表）。
