### ISSUE TITLE
脚本错误

### ISSUE THREAD

**Issue by SplitGemini** [dream7180/foobox-cn#31]
WSH 面板加强版 (JSPlaylist by Br3tt, Mod by dreamawake): Microsoft JScript 运行时错误:
'p.list.groups[...]' 为 null 或不是对象
文件: C:\Program Files (x86)\foobar2000\themes\foobox\js_panels\jsplaylist.js
行: 948, 列: 8
<源文本仅在编译时可用>

从资源管理器音乐工具选项卡（设foobox为默认播放器），选全部播放时经常出现这个问题，可能的复现方法是删除默认播放列表然后退出软件，然后资源管理器全部播放启动一次便会出现

![image](https://user-images.githubusercontent.com/34861918/90459825-fd279480-e134-11ea-9bba-92edb3abefb2.png)

**Comment by Dancewine** [comment]
我也遇到类似的播放列表脚本错误问题，一打开软件就是这样

WSH 面板加强版 (JSPlaylist by Br3tt, Mod by dreamawake): 无效指针  文件: D:\Music\foobox-cn\NSIS Source\foobar2000-core\themes\foobox\js_panels\jsplaylist\WSHplaylist.js
行: 332, 列: 7
<源文本仅在编译时可用>

小白求指点
