### ISSUE TITLE
深色界面时，菜单栏和状态栏还是白色

### ISSUE THREAD

**Issue by shieraaa** [dream7180/foobox-cn#310]
颜色选择了【foobox深色】，但是菜单栏和状态栏还是白色。请问是哪里设置问题吗？谢谢。

![image](https://github.com/user-attachments/assets/b91b7fb8-1ee2-41c7-87f8-ec5288bb2b2d)

**Comment by dream7180** [comment]
在这儿：
![图片](https://github.com/user-attachments/assets/742f3a81-43ae-4f93-a1ca-80a715a8862c)

**Comment by shieraaa** [comment]
好的，谢谢
