### ISSUE TITLE
更新到64位之后就无法使用主面板上的评星级功能了

### ISSUE THREAD

**Issue by Dropjack** [dream7180/foobox-cn#312]
因为从itunes过来养成的标星级来做不同类型的智能播放列表（不好意思只是个人的习惯），最近升级后突然不能直接在主面板上直接评星了（表现：点击星星之后就会自动取消），右击点击Playback Statisitcs里的等级是可以评星级的。我觉得有点麻烦，所以还是想提个issue，请求大神解决这个bug。感谢！

**Comment by dream7180** [comment]
未发现有问题，请使用 Asion 汉化版，其他有些汉化版的汉化文字不一样导致命令不一样。

https://github.com/user-attachments/assets/f527fdcc-994e-4b8a-aaf7-adef05edb724

**Comment by Dropjack** [comment]
啊，原来如此，我用的是原版的foobar2000，现在遇到的几个bug也都一起解决了

**Comment by dream7180** [comment]
原版的要配 foobox-en
