### ISSUE TITLE
使用6重制版主题时，设定点击关闭按钮后隐藏到托盘，点击关闭按钮会直接退出程序

### ISSUE THREAD

**Issue by mooeki** [dream7180/foobox-cn#319]
如题，版本7.37 x86
![屏幕截图 2024-12-01 134339](https://github.com/user-attachments/assets/72d52e7d-3dc7-45b9-a88a-77db84520917)
![2](https://github.com/user-attachments/assets/a120a3c4-9efa-4ef8-a0f7-2ce78ae29096)

**Comment by dream7180** [comment]
那个选项是对于不隐藏标题栏的情况下才生效，foobox 6的标题栏是虚拟的，直接执行exit动作。况且关闭最小化没意义，关闭到托盘还有点意义。
