### ISSUE TITLE
新版2.24 for Mac貌似也支持主题更换了？

### ISSUE THREAD

**Issue by venhow** [dream7180/foobox-cn#320]
请问大佬能不能看看也搞一套mac版本的？

2024-11-25

foobar2000 v2.24 has been released, for Windows and Mac OS.
This release changes the version numbering scheme, minor number for the intended release year.
While Windows version is mostly a maintenance/bugfix update, Mac version implements lots of previously-missing functionality, such as **user interface layout customization**.

**Comment by dream7180** [comment]
不关心mac，也没有mac
