### ISSUE TITLE
foobox_x86.cn.v7.38-1 点击关闭时最小化参数勾选不生效

### ISSUE THREAD

**Issue by Healyz** [dream7180/foobox-cn#324]
如题，用的foobar2000 v2.1.6X86版本，启用点击关闭时最小化选项，点击关闭程序直接退出。之前6.X版本是正常的
<img width="565" alt="微信图片_20241215135205" src="https://github.com/user-attachments/assets/77f468b9-3f0d-46e8-a268-6495e0171416" />

**Comment by dream7180** [comment]
是的，组件不一样了有些不同，要最小化请直接点最小化按钮
