### ISSUE TITLE
适配高分屏/调整字号时页面联动变化

### ISSUE THREAD

**Issue by H-Tung** [dream7180/foobox-cn#39]
现在调整字号时最上方标题栏宽度不变
导致图标被部分遮挡
设置中调整标题栏宽度无法改善这一问题

**Comment by LiYZ1994** [comment]
同有这问题，还希望能加入能调节右侧歌词栏和封面专辑图片的大小的功能

**Comment by ain-soph** [comment]
一个目前的替代方案是兼容性设置里面更改`高DPI设置`，最下面`替代高DPI缩放行为。缩放执行：`打上勾，选择`系统`。  
不过确实各个栏的宽度和高度没法直接调。并没有直接拖动宽度、高度的说法。

**Comment by H-Tung** [comment]
发现帮助文档里有写关于高分屏的问题,就是帮助文档藏得有点深...没扒文件夹的坏处

**Comment by ain-soph** [comment]
> 发现帮助文档里有写关于高分屏的问题,就是帮助文档藏得有点深...没扒文件夹的坏处

看到了，在foobox右上角。而且设置得有点繁琐。。你也可以试试我说的那个办法，感觉效果还行。  
![image](https://user-images.githubusercontent.com/13214530/104538205-6da1e700-55e9-11eb-907b-37faa605ba70.png)

**Comment by H-Tung** [comment]
好的,我都试试,谢谢!

**Comment by LiYZ1994** [comment]
> 
> 
> 好的,我都试试,谢谢!

我按照帮助文档的方法设置好了

**Comment by LiYZ1994** [comment]
> 
> 
> 一个目前的替代方案是别调字号，而是在兼容性设置里面更改`高DPI设置`，最下面`替代高DPI缩放行为。缩放执行：`打上勾，选择`系统`。当然了，这要求你的显示设置里面`缩放与布局`更改文本、应用等项目的大小选择一个较为合适的数值，我选的是150%。
> 不过确实各个栏的宽度和高度没法直接调。并没有直接拖动宽度、高度的说法。

我按照帮助文档的方法设置好了
