### ISSUE TITLE
音乐序号 ” # “ 显示错误

### ISSUE THREAD

**Issue by Majockred** [dream7180/foobox-cn#48]
![QQ图片20210208113639](https://user-images.githubusercontent.com/78713999/107173098-f4d45600-6a01-11eb-83a7-ce6186b1d4a4.png)
写入碟片编号后，#的状态显示异常，01号音乐会显示为0.01号音乐

**Comment by zhouhuajdsh** [comment]
碟片编号是discnumber，是数字序号1，2，3之类的。不是你这样写一串东西

**Comment by Majockred** [comment]
![TIM截图20210408183345](https://user-images.githubusercontent.com/78713999/114012743-4df12680-9899-11eb-8507-dfabdf3b83b5.png)
一样的

**Comment by Majockred** [comment]
> 碟片编号是discnumber，是数字序号1，2，3之类的。不是你这样写一串东西
![TIM截图20210408183345](https://user-images.githubusercontent.com/78713999/114012810-62cdba00-9899-11eb-935d-4c21a86a214a.png)

**Comment by Majockred** [comment]
没用的



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dream7180/foobox-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 晚上6:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dream7180/foobox-cn] 音乐序号 ” # “ 显示错误 (#48)





 
碟片编号是discnumber，是数字序号1，2，3之类的。不是你这样写一串东西

**Comment by Majockred** [comment]
![TIM截图20210408183345](https://user-images.githubusercontent.com/78713999/114013187-d96ab780-9899-11eb-9c44-08d6364f7d85.png)

**Comment by zhouhuajdsh** [comment]
有什么问题？是你自己不理解而已，X.XX----点前面是CD号，后面是音轨号，没有碟号就只会显示音轨号
$if2($num(%discnumber%,1)'.',)$if2($num(%tracknumber%,2),' ')不想显示CD号可以把前面删掉

**Comment by Majockred** [comment]
行吧




十二
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dream7180/foobox-cn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 晚上6:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dream7180/foobox-cn] 音乐序号 ” # “ 显示错误 (#48)





 
有什么问题？是你自己不理解而已，X.XX----点前面是CD号，后面是音轨号，没有碟号就只会显示音轨号
 $if2($num(%discnumber%,1)'.',)$if2($num(%tracknumber%,2),' ')不想显示CD号可以把前面删掉
