### ISSUE TITLE
是不是不支持dpi放大啊

### ISSUE THREAD

**Issue by basten1899** [dream7180/foobox-cn#49]
是不是不支持dpi放大啊, 4k 200% 还是原样

**Comment by wk4work** [comment]
+1
外层菜单放大被挡住了一般图标

**Comment by H-Tung** [comment]
在右上角菜单选项(向下的箭头)进入foobox帮助,有高分屏适配指南

**Comment by H-Tung** [comment]
提issue之前先搜一下已有的issue...

**Comment by wk4work** [comment]
> 在右上角菜单选项(向下的箭头)进入foobox帮助,有高分屏适配指南

有效, 多谢

**Comment by basten1899** [comment]
参数多试了几次 搞定
