### ISSUE TITLE
“设置关闭按钮最小化到系统托盘”的功能在哪？

### ISSUE THREAD

**Issue by mingy532** [dream7180/foobox-cn#66]
我知道默认版本的“设置关闭按钮最小化到系统托盘”在这个位置。
这个GUI的相关设置在哪里，似乎没有看到。
或者是直接不支持此操作的？

**Comment by mingy532** [comment]
已经找到了，抱歉打扰。

**Comment by mingy532** [comment]
找到的是 主窗口 -> 点击关闭时最小化（启用）。
但是这个只会设置为点击x的时候关闭窗口，任务栏里依旧有它的图标。 在按下tab+alt的时候它依旧会出现在窗口里。
我想要的是
显示-> 默认用户界面->后台与通知->窗口最小化和关闭->关闭:隐藏到系统托盘。

这样的功能，这样播放歌曲的时候就不会影响自己在不同的界面切换时候还要额外跳过一个音乐播放器。

**Comment by mingy532** [comment]
顺便问一下，默认的字体是7px,切换到10px之后最上面一行图标会被盖住下半边，有什么解决办法可以让整个界面一同调整吗？

**Comment by mingy532** [comment]
看起来没有。
还是用默认界面算了。

**Comment by grootsong** [comment]
> 找到的是 主窗口 -> 点击关闭时最小化（启用）。 但是这个只会设置为点击x的时候关闭窗口，任务栏里依旧有它的图标。 在按下tab+alt的时候它依旧会出现在窗口里。 我想要的是 显示-> 默认用户界面->后台与通知->窗口最小化和关闭->关闭:隐藏到系统托盘。
> 
> 这样的功能，这样播放歌曲的时候就不会影响自己在不同的界面切换时候还要额外跳过一个音乐播放器。

不行呀，如果这样设置了，点关闭以后，软件直接就关闭了。版本V6.1.6.10

**Comment by grootsong** [comment]
> 看起来没有。 还是用默认界面算了。

我找到设置方法了。
![image](https://user-images.githubusercontent.com/63644470/160571360-9b5a7ed3-42d7-4cbb-9440-67f54f421489.png)
点击关闭时最小化选择启用，然后把下边的“隐藏任务栏图标”勾选上。这样按TAB+ALT键就不会出现窗口了。

**Comment by KargathEx** [comment]
感谢回复，不过因为放大界面之后最上面一行的像素对不上，所以我已经在用原来的界面了。
