### ISSUE TITLE
更新到v6.1.6.7后，歌曲的评级不显示

### ISSUE THREAD

**Issue by aka2ye** [dream7180/foobox-cn#73]
刚从v1.4.3升级到了v6.1.6.7，评级写入标签都是选择了的，但是之前的播放列表导入到新版本后，歌曲的评级全部消失了是怎么回事？我也试了把一首歌在最新版本的foobox里面写入评级，在老版本里面打开后，评级依然是不显示的，证明评级没有成功写入标签。除了把 “同时写入文件标签及playcount记录” 勾上，还需要怎么操作来保存评级到标签？ 谢谢！

**Comment by ConnorLH** [comment]
有导入导出功能

**Comment by goeway** [comment]
借楼。。。我的是音乐标签里有评级信息，但在播放列表中评级显示不出来
