### ISSUE TITLE
foobar 2000安装损坏-组件来自 foobar2000其他版本：专辑列表，版本：1.6.5 请重装foobar2000修正这个问题。

### ISSUE THREAD

**Issue by klxq520** [dream7180/foobox-cn#90]
升级了最新版变成这样了，点取消可以正常打开播放，点确定就不行，每次启动都会
![搜狗截图20220116113038](https://user-images.githubusercontent.com/45682501/149646219-27147493-3372-4e7f-be7f-ff7963a906f1.png)

**Comment by klxq520** [comment]
请问怎么修复这个问题啊？

**Comment by Pinwee** [comment]
我也有这个问题

**Comment by dewrfe53535** [comment]
同样遇到了
以压缩包的形式打开安装程序,找到components/foo_albumlist.dll替换后解决

**Comment by klxq520** [comment]
> 同样遇到了 以压缩包的形式打开安装程序,用里面的文件替换对应位置的components/foo_albumlist.dll后解决

非常感谢，真的可以了
