### ISSUE TITLE
问题：无法改变分组

### ISSUE THREAD

**Issue by Howard-Zhou-77** [dream7180/foobox-cn#93]
操作：

- 点标题栏上的「foobox设置」
- 点「分组」选项卡
- 点击一个其他的模板并双击/按<kbd>Enter</kbd>
- 切换回播放列表

预计效果：

播放列表切换到按设置的分组方式分组。

实际上：

播放列表并未按设置的分组方式分组，而是仍然处于`专辑 (简单)`的分组方式中。

**Comment by dream7180** [comment]
那里是编辑分组，选分组在播放列表顶部（栏目那行）右键打开菜单进行选择
