### ISSUE TITLE
win11微软输入法提示框出现在左上角

### ISSUE THREAD

**Issue by CJunliang** [dream7180/foobox-cn#97]
![image](https://user-images.githubusercontent.com/48561974/159939541-5ec93b68-4353-4060-b9a6-b26c48b2510c.png)

**Comment by github-24** [comment]
> ![image](https://user-images.githubusercontent.com/48561974/159939541-5ec93b68-4353-4060-b9a6-b26c48b2510c.png)

我也这样，解决了吗

**Comment by dream7180** [comment]
不能光标跟随，组件功能问题
